runtime: php
env: flex

runtime_config:
  document_root: public

skip_files:
  - .env

env_variables:
  APP_ENV: production
  APP_DEBUG : false
  APP_KEY: base64:zmsb4mUVPaeqH+owewToiiI7u24bI6XmNUrL6fpib3s=

  CACHE_DRIVER: file
  SESSION_DRIVER: file

  APP_LOG: errorlog
  APP_TIMEZONE: UTC

  DB_CONNECTION: mysql
  DB_HOST: 34.95.180.7
  DB_PORT: 3306
  DB_DATABASE: pagueTop
  DB_USERNAME: root
  DB_PASSWORD: hmNlNEEwJf4nF3cE
  DB_SOCKET: /cloudsql/paguetop:southamerica-east1:pague-top-database


  QUEUE_DRIVER: database

  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.sparkpostmail.com
  MAIL_PORT: 587
  MAIL_USERNAME: sparkpost_username
  MAIL_PASSWORD: 12131214241

  LOG_DELETE:  true

  GOOGLE_VISION_PROJECT_ID : apipaguetop

beta_settings:
  cloud_sql_instances: paguetop:southamerica-east1:pague-top-database
